name: Deploy Ecommerce App

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/ecommerce/**'
      - 'scripts/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'apps/ecommerce/**'
      - 'scripts/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/ecommerce

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.14.0'

    - name: Install pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 9.0.0
        run_install: false

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_ENV

    - name: Setup pnpm cache
      uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: pnpm install

    - name: Run tests
      run: pnpm test

    - name: Build
      run: pnpm build:production
      env:
        VITE_APP_ENV: production
        # Agrega aquí otras variables de entorno si son necesarias

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to S3
      run: |
        aws s3 sync dist/ s3://${{ secrets.AWS_S3_BUCKET }} --delete

    - name: Invalidate CloudFront
      if: github.ref == 'refs/heads/main'
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"