name: Deploy Ecommerce App

on:
  push:
    branches: [ main ]
    paths:
      - 'apps/ecommerce/**'
      - '.github/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'apps/ecommerce/**'
      - 'github/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/ecommerce

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.14.0'

    - name: Install pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 9.0.0
        run_install: false

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_ENV

    - name: Setup pnpm cache
      uses: actions/cache@v4
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      run: pnpm install

    - name: Run tests
      run: pnpm test

    - name: Build
      run: pnpm build:production
      env:
        VITE_APP_ENV: production
        # Agrega aquí otras variables de entorno si son necesarias

    - name: Update AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update

    - name: Configure AWS Credentials
      env:
        AWS_ACCESS_KEY_ID: AKIAUWHICA6R5YZKUJXU
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
      run: |
        aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
        aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
        aws configure set default.region $AWS_DEFAULT_REGION
        aws sts get-caller-identity

    - name: Deploy to S3
      if: github.ref == 'refs/heads/main'
      env:
        AWS_ACCESS_KEY_ID: AKIAUWHICA6R5YZKUJXU
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
      run: |
        aws s3 sync dist/ s3://app-ecommerce-test --delete

    - name: Invalidate CloudFront
      if: github.ref == 'refs/heads/main'
      env:
        AWS_ACCESS_KEY_ID: AKIAUWHICA6R5YZKUJXU
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
      run: |
        aws cloudfront create-invalidation --distribution-id E1SYRPK2TG9M7T --paths "/*"